# docker-compose.yml

# Usage: docker-compose up -d

services:
  web:
    depends_on:
      - db
    restart: on-failure:4
    build:
        dockerfile: Dockerfile
        tags:
          - anilssonstrom/moviedb:v4
          - anilssonstrom/moviedb:latest
    ports:
      - 5000:80
    environment:
      FLASK_DEBUG: true

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306
    volumes:
      - "./.database:/var/lib/mysql"   # lokala mappen : mappen i containern
